spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calificaciondb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8086