spring:
  datasource:
    url: jdbc:mysql://localhost:3306/librodb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect    show-sql: true
server:  port: 8083
    